# Generated by Django 5.2.16 on 2026-07-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(choices=[('Mitsubishi', 'Mitsubishi'), ('Siemens', 'Siemens'), ('Omron', 'Omron'), ('Allen Bradley', 'Allen Bradley')], max_length=50)),
                ('protocol', models.CharField(choices=[('MELSEC', 'MELSEC'), ('Modbus TCP', 'Modbus TCP'), ('EtherNet/IP', 'EtherNet/IP'), ('Profinet', 'Profinet')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=1025)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plcs',
                'ordering': ['name'],
            },
        ),
    ]
