# Generated by Django 5.2.16 on 2026-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc',
            name='protocol',
        ),
        migrations.AddField(
            model_name='plc',
            name='series',
            field=models.CharField(choices=[('iQ-R', 'iQ-R')], default='iQ-R', max_length=50),
        ),
        migrations.AlterField(
            model_name='plc',
            name='manufacturer',
            field=models.CharField(choices=[('Mitsubishi', 'Mitsubishi')], default='Mitsubishi', max_length=50),
        ),
    ]
