# Generated by Django 5.2.16 on 2026-07-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0002_remove_plc_protocol_plc_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('BOOL', 'BOOL'), ('INT', 'INT'), ('REAL', 'REAL'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('WORD', 'WORD'), ('DWORD', 'DWORD')], max_length=20)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='blue', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_writable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='plc.plc')),
            ],
            options={
                'db_table': 'plc_tags',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('plc', 'address'), name='unique_plc_address')],
            },
        ),
    ]
