# Generated by Django 5.2.16 on 2026-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0003_plctag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plctag',
            name='color',
            field=models.CharField(default='#22C55E', max_length=20),
        ),
    ]
