# Generated by Django 5.2.16 on 2026-07-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0004_alter_plctag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCTagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(default='GOOD', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_value', to='plc.plctag')),
            ],
            options={
                'db_table': 'plc_tag_values',
            },
        ),
    ]
