# Generated by Django 5.2.16 on 2026-07-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0005_plctagvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('READ', 'READ'), ('WRITE', 'WRITE')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='plc.plc')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='plc.plctag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plc_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plc_operation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
