# Generated by Django 5.2.16 on 2026-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0006_plcoperationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plctag',
            name='color',
        ),
        migrations.AddField(
            model_name='plctag',
            name='high_color',
            field=models.CharField(default='#EF4444', max_length=20),
        ),
        migrations.AddField(
            model_name='plctag',
            name='low_color',
            field=models.CharField(default='#22C55E', max_length=20),
        ),
        migrations.AddField(
            model_name='plctag',
            name='medium_color',
            field=models.CharField(default='#FACC15', max_length=20),
        ),
        migrations.AddField(
            model_name='plctag',
            name='off_color',
            field=models.CharField(default='#6B7280', max_length=20),
        ),
        migrations.AddField(
            model_name='plctag',
            name='on_color',
            field=models.CharField(default='#22C55E', max_length=20),
        ),
    ]
