# Generated by Django 5.2.16 on 2026-07-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0007_remove_plctag_color_plctag_high_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCVisualizationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_type', models.CharField(choices=[('motor', 'Motor'), ('pump', 'Pump'), ('valve', 'Valve'), ('tank', 'Tank'), ('fan', 'Fan')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualization_objects', to='plc.plctag')),
            ],
            options={
                'db_table': 'plc_visualization_objects',
            },
        ),
    ]
