# Generated by Django 5.2.16 on 2026-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0008_plcvisualizationobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plcvisualizationobject',
            name='svg_type',
            field=models.CharField(choices=[('motor', 'Motor'), ('pump', 'Pump'), ('button', 'Button'), ('tank', 'Tank')], max_length=50),
        ),
    ]
