# Generated by Django 5.2.16 on 2026-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0009_alter_plcvisualizationobject_svg_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plcvisualizationobject',
            constraint=models.UniqueConstraint(fields=('tag',), name='unique_visualization_tag'),
        ),
    ]
